package nimbus.ui;

import java.util.Scanner;

import nimbus.exception.NimbusException;
import nimbus.task.Task;
import nimbus.task.TaskList;

/**
 * Represents the user interface of the Nimbus application.
 * It is responsible for reading user input and displaying messages to the user.
 * <p>
 * Message text is generated by the {@code format*} methods, which return
 * plain {@link String} content with no CLI-specific decoration. The
 * {@code print*} methods wrap that content with the CLI's horizontal-line
 * borders and write it to standard output. This split lets other front ends
 * (e.g. a GUI) reuse the exact same wording via the {@code format*} methods
 * without depending on {@code System.out} or the CLI's border style.
 */
public class Ui {

    public static final String HORIZONTAL_LINE = "____________________________________________________________";
    public static final String BANNER = "#   #  #####  #   #  ####   #   #   ####\n"
            + "##  #    #    ## ##  #   #  #   #  #     \n"
            + "# # #    #    # # #  ####   #   #   ###  \n"
            + "#  ##    #    #   #  #   #  #   #     #  \n"
            + "#   #  #####  #   #  ####    ###   ####  \n";
    private final Scanner scanner;

    /**
     * Constructs a Ui that reads user input from standard input.
     */
    public Ui() {
        this.scanner = new Scanner(System.in);
    }

    /**
     * Reads a single line of input entered by the user.
     *
     * @return The line of text entered by the user.
     */
    public String readCommand() {
        return scanner.nextLine();
    }

    // ---------------------------------------------------------------
    // format* methods: build message content only, no printing, no borders.
    // ---------------------------------------------------------------

    /**
     * Builds the welcome greeting shown at startup (banner not included;
     * see {@link #BANNER}).
     *
     * @return The welcome message text.
     */
    public String formatWelcome() {
        return "Hello! I'm Nimbus.\nWhat can I do for you?";
    }

    /**
     * Builds the farewell message shown when the application exits.
     *
     * @return The farewell message text.
     */
    public String formatExitMessage() {
        return "Bye. Hope to see you again soon!";
    }

    /**
     * Builds a listing of every task currently in the given task list.
     *
     * @param taskList The task list to display.
     * @return The formatted task list text.
     */
    public String formatTaskList(TaskList taskList) {
        return "Here are the tasks in your list:\n" + taskList.toString();
    }

    /**
     * Builds confirmation that a task was added, including the updated task
     * count.
     *
     * @param task     The task that was added.
     * @param taskList The task list the task was added to.
     * @return The formatted confirmation text.
     */
    public String formatAddTask(Task task, TaskList taskList) {
        return "Got it. I've added this task:\n" + task.toString() + "\n" + formatTaskSize(taskList);
    }

    /**
     * Builds confirmation that a task was deleted, including the updated task
     * count.
     *
     * @param task     The task that was removed.
     * @param taskList The task list the task was removed from.
     * @return The formatted confirmation text.
     */
    public String formatDeleteTask(Task task, TaskList taskList) {
        return "Noted. I've removed this task:\n" + task.toString() + "\n" + formatTaskSize(taskList);
    }

    /**
     * Builds confirmation that a task was marked as done.
     *
     * @param task The task that was marked done.
     * @return The formatted confirmation text.
     */
    public String formatMarkTask(Task task) {
        return "Nice! I've marked this task as done:\n" + task.toString();
    }

    /**
     * Builds confirmation that a task was marked as not done.
     *
     * @param task The task that was marked not done.
     * @return The formatted confirmation text.
     */
    public String formatUnmarkTask(Task task) {
        return "OK, I've marked this task as not done yet:\n" + task.toString();
    }

    /**
     * Builds a line describing the current number of tasks in the given
     * task list.
     *
     * @param taskList The task list whose size is described.
     * @return The formatted task-count text.
     */
    public String formatTaskSize(TaskList taskList) {
        return "Now you have " + taskList.getSize() + " tasks in the list.";
    }

    /**
     * Builds confirmation that tasks were successfully loaded from file.
     *
     * @param taskCount The number of tasks loaded.
     * @return The formatted confirmation text.
     */
    public String formatTasksLoaded(int taskCount) {
        return "Successfully loaded " + taskCount + " tasks from file.";
    }

    /**
     * Builds confirmation that tasks were successfully saved to file.
     *
     * @param taskCount The number of tasks saved.
     * @return The formatted confirmation text.
     */
    public String formatTasksSaved(int taskCount) {
        return "Successfully saved " + taskCount + " tasks to file.";
    }

    /**
     * Builds the error message carried by the given exception.
     *
     * @param e The exception whose message is formatted.
     * @return The formatted error text.
     */
    public String formatError(NimbusException e) {
        return e.getMessage();
    }

    // ---------------------------------------------------------------
    // print* methods: CLI-only. Wrap format* output with borders and
    // write it to standard output.
    // ---------------------------------------------------------------

    /**
     * Prints an arbitrary message wrapped in the CLI's horizontal-line
     * borders. Used by the CLI loop to display whatever response
     * {@code Nimbus.getResponse(String)} returns, without needing a
     * command-specific print method for each case.
     *
     * @param message The message text to print.
     */
    public void printMessage(String message) {
        System.out.println(HORIZONTAL_LINE);
        System.out.println(message);
        System.out.println(HORIZONTAL_LINE);
    }

    /**
     * Prints the welcome banner and greeting shown at startup.
     */
    public void showWelcome() {
        System.out.println(HORIZONTAL_LINE);
        System.out.println(BANNER);
        System.out.println(formatWelcome());
        System.out.println(HORIZONTAL_LINE);
    }

    /**
     * Prints the farewell message shown when the application exits.
     */
    public void showExitMessage() {
        System.out.println(HORIZONTAL_LINE);
        System.out.println(formatExitMessage());
        System.out.println(HORIZONTAL_LINE);
    }

    /**
     * Prints every task currently in the given task list.
     *
     * @param taskList The task list to display.
     */
    public void printTaskList(TaskList taskList) {
        System.out.println(HORIZONTAL_LINE);
        System.out.println(formatTaskList(taskList));
        System.out.println(HORIZONTAL_LINE);
    }

    /**
     * Prints confirmation that a task was added, followed by the updated task
     * count.
     *
     * @param task     The task that was added.
     * @param taskList The task list the task was added to.
     */
    public void printAddTask(Task task, TaskList taskList) {
        System.out.println(HORIZONTAL_LINE);
        System.out.println(formatAddTask(task, taskList));
        System.out.println(HORIZONTAL_LINE);
    }

    /**
     * Prints confirmation that a task was deleted, followed by the updated task
     * count.
     *
     * @param task     The task that was removed.
     * @param taskList The task list the task was removed from.
     */
    public void printDeleteTask(Task task, TaskList taskList) {
        System.out.println(HORIZONTAL_LINE);
        System.out.println(formatDeleteTask(task, taskList));
        System.out.println(HORIZONTAL_LINE);
    }

    /**
     * Prints confirmation that a task was marked as done.
     *
     * @param task The task that was marked done.
     */
    public void printMarkTask(Task task) {
        System.out.println(HORIZONTAL_LINE);
        System.out.println(formatMarkTask(task));
        System.out.println(HORIZONTAL_LINE);
    }

    /**
     * Prints confirmation that a task was marked as not done.
     *
     * @param task The task that was marked not done.
     */
    public void printUnmarkTask(Task task) {
        System.out.println(HORIZONTAL_LINE);
        System.out.println(formatUnmarkTask(task));
        System.out.println(HORIZONTAL_LINE);
    }

    /**
     * Prints the current number of tasks in the given task list.
     *
     * @param taskList The task list whose size is printed.
     */
    public void printTaskSize(TaskList taskList) {
        System.out.println(formatTaskSize(taskList));
    }

    /**
     * Prints confirmation that tasks were successfully loaded from file.
     *
     * @param taskCount The number of tasks loaded.
     */
    public void showTasksLoaded(int taskCount) {
        System.out.println(HORIZONTAL_LINE);
        System.out.println(formatTasksLoaded(taskCount));
        System.out.println(HORIZONTAL_LINE);
    }

    /**
     * Prints confirmation that tasks were successfully saved to file.
     *
     * @param taskCount The number of tasks saved.
     */
    public void showTasksSaved(int taskCount) {
        System.out.println(HORIZONTAL_LINE);
        System.out.println(formatTasksSaved(taskCount));
        System.out.println(HORIZONTAL_LINE);
    }

    /**
     * Prints the error message carried by the given exception.
     *
     * @param e The exception whose message is displayed to the user.
     */
    public void printError(NimbusException e) {
        System.out.println(HORIZONTAL_LINE);
        System.out.println(formatError(e));
        System.out.println(HORIZONTAL_LINE);
    }
}
